use aegis_db;
-- Create DPS_USER table
CREATE TABLE DPS_USER (
    ID VARCHAR(40) NOT NULL,
    LOGIN VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(40),
    LAST_NAME VARCHAR(40),
    EMAIL VARCHAR(100),
    PRIMARY KEY (ID),
    UNIQUE (LOGIN)
);
select * from DPS_USER;
 
 
-- Create DSS_DPS_EVENT table
CREATE TABLE DSS_DPS_EVENT (
    ID VARCHAR(32) NOT NULL,
    TIMESTAMP DATETIME,
    SESSIONID VARCHAR(32),
    PROFILEID VARCHAR(100)
);
 
select * from DSS_DPS_EVENT;
DELETE FROM DSS_DPS_EVENT;
SET SQL_SAFE_UPDATES = 0;
 
INSERT INTO DPS_USER (ID, LOGIN, FIRST_NAME, LAST_NAME, EMAIL)
VALUES (
    UUID(), -- generates a unique string ID
    'testuser@example.com',
    'Test',
    'User',
    'testuser@example.com'
);

ALTER TABLE DSS_DPS_EVENT
ADD COLUMN NAME VARCHAR(100),
ADD COLUMN EMAIL VARCHAR(100);
 
ALTER TABLE DSS_DPS_EVENT MODIFY ID VARCHAR(40);
ALTER TABLE DSS_DPS_EVENT MODIFY TIMESTAMP DATETIME;